### ISSUE TITLE
Fields not working properly on Widgets page

### ISSUE THREAD

**Issue by rahulnever2far** [Codestar/codestar-framework#322]
I just downloaded and added the latest commit ([39f5f72](https://github.com/Codestar/codestar-framework/commit/39f5f722b3833f264ec420f83e30cebe384d9686)) to my theme.

Color picker and image fields stopped worked on the Widgets page. It seems like all fields that use JS stopped working.

Also, color picker appears twice when a widget is added in Customizer as in #316.

**Comment by Codestar** [comment]
Hi,

Yes it is right, thanks for report, i fixed it now. re-download latest changes. btw latest commit is https://github.com/Codestar/codestar-framework/commit/cbbe8971c93951da4844a1db0b2bdf075744865b

**Comment by rahulnever2far** [comment]
Fields are work perfectly on the Widgets now.

But the color picker is still appearing twice when a widget is added in Customizer.

**Comment by Codestar** [comment]
Uh, interesting. i tested it again now and one color picker in my localhost? maybe a cache? because i added only #widgets-right for reload plugins.

```javascript
$('.cs-framework, .wp-customizer, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();
```

Send me your widget configure php via https://gist.github.com/

**Comment by rahulnever2far** [comment]
Color picker appears twice when you add new Widget in Customizer. After you save Customizer settings and reload the Customizer, color picker appears once like it should.

I'm using the following code to add the field:
```PHP
$test_value = esc_attr( $instance[ 'test' ] );
$test_field = array(
  'id'      => $this->get_field_name( 'test' ),
  'name'    => $this->get_field_name( 'test' ),
  'type'    => 'color_picker',
  'title'   => esc_html__( 'Color', 'kirki' ),
  'default' => '#ff0078',
);
echo cs_add_element( $test_field, $test_value );
```
Changing this line in [cs-framework.js#L1432](https://github.com/Codestar/codestar-framework/blob/master/assets/js/cs-framework.js#L1432) fixes the issue.
```PHP
// from
$('.cs-framework, .wp-customizer, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();

// to
$('.cs-framework').CSFRAMEWORK_RELOAD_PLUGINS();
```

**Comment by Codestar** [comment]
Hi,

Ups, very interesting. if you use this code:

```php
$('.cs-framework').CSFRAMEWORK_RELOAD_PLUGINS();
```

It will not work, when you refresh page? did you test it ? refresh widgets page and see widget.

**Comment by rahulnever2far** [comment]
I'm not talking about the Widget page. I confirmed that fields are working fine on the Widgets page.

The issue is color picker appears twice when you **add a new Widget in Customizer**. :)

PS: How did you make that gif? That would be very helpful while reporting issues.

**Comment by NoahjChampion** [comment]
@Codestar is a .gif pro. 

There are a few apps that allow converting a screencast to a .gif. I have one, but would also like to know which you use @Codestar

**Comment by Codestar** [comment]
@rahulnever2far oh my god :smiley: i understand it now finally :smile: Can you try this code and tell me result. check everywhere is working normally?

```javascript
$('.cs-framework, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();
```

About gif screencast. I am using linux [Ubuntu](http://www.ubuntu.com/) pc. You know everything is easy in linux. It is a simple clean shell script. Original scripts created by RobW on [askubuntu](http://askubuntu.com/a/201018)

 I :heart: Ubuntu

@NoahjChampion

**Comment by rahulnever2far** [comment]
This change made it work in both Widgets page and Customizer :100: 

Oh my god, I love Linux too. I prefer a different distro though, Fedora. Linux is so much better than Windows especially if you are a developer :+1:  But I still need to work in Windows just because my designer uses Photoshop :cry: I wish I could somehow make Photoshop (or at least PSDs) work in Linux :sob:

**Comment by Codestar** [comment]
@rahulnever2far wow nice. Yes PS is problem. sometimes i am using Virtualbox-Windows for small psd works. i abandoned to use "Windows" 5-6 years ago. Linux is great! :+1: Let's support Linux.

Thanks for test, I updated the code now. https://github.com/Codestar/codestar-framework/commit/ac7422bf1f7e80de1f16897e66122ec7ad76b724

**Comment by NoahjChampion** [comment]
@Codestar @rahulnever2far 

What do you think about [Cloud9](http://zombo.com/)? 

I don't know what Ubuntu is, but Cloud9 is what I use and it uses Ubuntu. I started using Cloud9 because it allowed me to work in the cloud and use less apps and tools. I use mac though. Since you guys are pros, maybe you can give some feedback I can understand.

**Comment by Codestar** [comment]
@NoahjChampion It is a online code editor and uses Ubuntu as said you. If you are not a **team** and you have a **Ubuntu** i think you do not need it. :smile: because operating system will fast than a browser script (for small projects). But i can say Cloud9 is great really, for eg, you can test your a wordpress theme in 300+ browser/OS combinations Shortly only you need 5-10% features of Cloud9. Actually it is useful for large team projects. If you are alone and a wordpress developer, does not needed :+1: It is my opinion. :smile:

**Comment by Codestar** [comment]
@NoahjChampion 

Btw, Some similar projects.

http://www.koding.com/
https://www.nitrous.io/
https://www.heroku.com/

**Comment by NoahjChampion** [comment]
@Codestar thanks for the links and report. :) 

I need Cloud9. I've been able to speed up development and I love it :)

I only searched for an online development because I just can't find the perfect code editor. Cloud9 uses ACE, which is not my favorite, but I made myself get used to it. It plays out better for me because chrome has extensions for everything else, so now I can se just one screen space for most things. 

But I also wanted to develop in the cloud because I can develop for a client in real time and they can see the preview live. I don't have to develop localhost, then push the site site to a live domain for client preview/approval. All I do now is send the client the Cloud9 link :) It has been a lot faster for me. 

But, once I release my theme I plan to have a team as well, so this should work out nicely. The computer should run faster, but it depends because of what apps I am running on my computer, which is multiple apps :( MAMP, Editors, Database, Minifiers, File Renames, plus my other apps, Music, Email, Photoshop, Project Timer, Folder Manager, etc.) Now I just run Cloud9 browser, time tracker, and music. And I can drag and drop to upload files and folders to Cloud9. 

Anyway, you know this obviously :) But I'm glad I found it! I love it now. It is good for me. I have no team yet, but I am a 1 person army ;)

**Comment by Codestar** [comment]
@NoahjChampion yes yes, i agree totally. it is useful for clients. i wrote my words for a alone full-time themeforest author :) we have not clients :smile_cat: if you have custom projects, it is powerful tool. 

Good Luck for projects :wink:

**Comment by NoahjChampion** [comment]
@Codestar 

Thanks, and just to say... Cloud9 auto-saving speeds up production a lot 👍 

Yes, I have clients and custom projects, so this will be my first theme. I may become full-time theme/plugin author because of sales, I expect. We will see. #FingersCrossed

Okay about ACE Editor. Good news.

**Comment by kenthd** [comment]
@Codestar 
How I can use the dependency on the widget page? I tried and it does not work, this is my code
`
$number    = isset( $instance['number'] ) ? absint( $instance['number'] ) : 5;
$show_date = isset( $instance['show_date'] ) ? (bool) $instance['show_date'] : false;
/**
 * Create element Number of posts to show
 */
    $number_args = array(
      'id'      => $this->get_field_name( 'number' ),
      'name'    => $this->get_field_name( 'number' ),
      'type'    => 'text',
      'title'   => esc_html__( 'Number of posts to show', 'codestar' ),
      'default' => '5',
      'dependency' => array( 'show_date', '==', 'true' ),
    );
    echo cs_add_element( $number_args, $number );

/**
 * Create element Display post date
 */
    $show_date_args = array(
      'id'      => $this->get_field_name( 'show_date' ),
      'name'    => $this->get_field_name( 'show_date' ),
      'type'    => 'checkbox',
      'title'   => '',
      'label'   => esc_html__( 'Display post date?', 'codestar' ),
      'default' => false,
    );
    echo cs_add_element( $show_date_args, $show_date );
`

Thanks ;)

**Comment by rahulnever2far** [comment]
@kenthd Instead of 
```PHP
'dependency' => array( 'show_date', '==', 'true' ),
```
Use the following for dependencies in widgets:
```PHP
'dependency' => array( $this->get_field_name( 'show_date' ), '==', '1' ),
```

PS: I think it is better to create a separate issue for each issue/question because it helps others who are looking for the same thing :smile:

**Comment by Codestar** [comment]
Hey @kenthd follow @rahulnever2far solution. it is correct way. :+1:

**Comment by kenthd** [comment]
@rahulnever2far perfect, it did work. Thanks very much :ok_hand:

**Comment by kenthd** [comment]
@Codestar I did using the dependency on the customize page, but it not working.
This is my code:

```
array(
  'name'    => 'site_layouts',
  'default' => 'fullwidth',
  'control' => array(
    'label'   => esc_html__( 'Site Layout', 'codestar' ),
    'type'    => 'radio',
    'choices' => array(
      'fullwidth' => esc_html__( 'Full Width', 'codestar' ),
      'boxed'     => esc_html__( 'Boxed', 'codestar' ),
    )
  )
),

/**
 * Background body
 */
  array(
    'name'          => 'background_body',
    'control'       => array(
      'type'      => 'cs_field',
      'options'   => array(
        'type'       => 'image',
        'title'      => esc_html__( 'Background Body', 'codestar' ),
        'dependency' => array( 'site_layouts_boxed', '==', 'true' ),
      ),
    ),
  ),
```
Attachment image: http://prntscr.com/b9cfyh

You can give me advice? 
Thanks very much :+1:

**Comment by Codestar** [comment]
Hey, @kenthd 

You are using default wp core radio field with codestar framework field. and default wp core radio do not have dependency attributes. as you know, this dependency feature only working with codestar framework fields.

Correct usage:
```php
// Converted radio field to codestar radio here
array(
  'name'    => 'site_layouts',
  'default' => 'fullwidth',
  'control' => array(
    'type'    => 'cs_field',
    'options' => array(
      'type'      => 'radio',
      'title'     => esc_html__( 'Site Layout', 'codestar' ),
      'options'   => array(
        'fullwidth' => esc_html__( 'Full Width', 'codestar' ),
        'boxed'     => esc_html__( 'Boxed', 'codestar' ),
      )
    )
  )
),

// this is same, no touched.
array(
  'name'    => 'background_body',
  'control' => array(
    'type'    => 'cs_field',
    'options' => array(
      'type'       => 'image',
      'title'      => esc_html__( 'Background Body', 'codestar' ),
      'dependency' => array( 'site_layouts_boxed', '==', 'true' ),
    ),
  ),
),
```

**Comment by kenthd** [comment]
@Codestar It's did working, thanks very much :100:

**Comment by Codestar** [comment]
You're welcome @kenthd
